apiVersion: v1
kind: Secret
metadata:
  name: arcade-fluentd-sumologic-setup
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: arcade-fluentd-sumologic
    chart: "sumologic-2.18.1"
    release: "arcade-fluentd"
    heritage: "Helm"
data:
  SUMOLOGIC_ACCESSID: {access_id}
  SUMOLOGIC_ACCESSKEY: {access_key}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: arcade-fluentd-kube-promet-prometheus-scrape-confg
  namespace: fluentd
  labels:
    app: kube-prometheus-stack-prometheus-scrape-confg
    chart: kube-prometheus-stack-12.10.0
    release: "arcade-fluentd"
    heritage: "Helm"
data:
  additional-scrape-configs.yaml: ""
