#!/usr/bin/env python3
'''
{myname TODO header string} -- Needs Description.
'''
# @depends: boto3, python (>=2.7)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__="Reports on state of online/running GRV."

import os
import sys
import boto3
import grv

dothere = os.path.dirname(os.path.normpath(sys.argv[0]))
myhier = os.path.dirname(dothere)
grv_conf= grv.source(str(myhier + '/etc/grv.conf'))

if description is "":
    description = "No description yet."
_me = os.path.basename(sys.argv[0])
_me_cmd = _me.split('-', 1)[1]
_desc="""
  {_me_cmd} - {description}
"""
try:
    if _exit is None:
        _exit = 0
except:
    _exit = 0
try:
    if _fdout is None:
        if _exit == 0:
            _fdout = sys.stdout
        else:
            _fdout = sys.stderr
except:
    _fdout = sys.stdout


print >> _fdout, _desc.format(_me_cmd=_me_cmd, description=description,)

sys.exit(_exit)
