#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
galagazero-read -- GALAGA read status of ARCADE/Account Infrastructure components.
'''

# @depends: boto3, python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Print status of ARCADE/Account components status."


import argparse
import logging
import os
from pprint import pprint
import sys

from arclib import common
from arclib import grv
from arclib import log
from arclib import secrets_manager
from arclib import storage
from arclib.common import print_status


def read_super_service_status(arcade_name: str, gsd_data: dict):
    # TODO: return True right away until we get this confirmed.
    return True

    ACCOUNT_NUMBER = os.getenv('GALAGA_SUPER_SERVICE_ACCOUNT')
    SUPER_SERVICE_ROLE_NAME = os.getenv('GALAGA_SUPER_SERVICE_ROLE_NAME')
    SUPER_SERVICE_PREFIX = os.getenv('GALAGA_SUPER_SERVICE_PREFIX')

    check_status = grv.check_if_arcade_policy(arcade_name=arcade_name, component_name='SecretsManagerSS')
    logging.info(check_status)
    print_status(check_status)

    if check_status:
        check_if_lambda = secrets_manager.find_lambda(arcade_name=arcade_name,
                                                      function_name='secrets_manager_sync')
        if check_if_lambda:
            print_status(check_if_lambda)
            logging.info(check_if_lambda)
            if grv.find_role('LambdaSSRoleExecution')['Role']['RoleName'] == 'LambdaSSRoleExecution':
                return True

    return False


def main():
    """
    %(prog)s - Display ARCADE/Account GALAGA components information
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path with filename in s3")

    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            sys.exit(1)
    arcade_name = args.arcade

    session = common.setup_arcade_session(arcade_name)

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    if args.path:
        gsd_data = storage.s3_json_to_dict(session, bucket, f"{args.path}")
        if not gsd_data:
            sys.exit(1)
    else:
        gsd_data = {
                    "name": "galagazero",
                    "component_type": "galagazero",
                    "version": 1,
                    "description": "Data for GALAGA zero",
                    "services": {
                        "parameterstore": {
                            "service_options": {}
                        }
                    }
                   }

    pprint(gsd_data)

    check_status = grv.check_if_arcade_policy(arcade_name, 'parameterstore')
    logging.info(check_status)
    print_status(check_status)

    sys.exit(0)


if __name__ == '__main__':
    main()
