#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
log-relay -- Read status of ARCADE scoped log relay.
'''

# @depends: python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Read status of ARCADE scoped log relay."

import argparse
import logging
import os
from pprint import pprint
import sys

import boto3

from arclib import alb
from arclib import asg
from arclib import common
from arclib import dns
from arclib import log
from arclib import storage


def main():
    """
    %(prog)s - Create the ARCADE log relay ASG.
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path to filename in s3", required=True)

    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            parser.print_help()
            sys.exit(1)
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    session = boto3.session.Session()

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    if not gsd_data:
        sys.exit(1)
    pprint(gsd_data)

    arcade_domain = arcade_name.replace('_', '-')
    arcade_safe_name = arcade_name.replace('_', '').replace('.', '-')
    asg_data = gsd_data['services']['asg']['service_options']
    cluster_prefix = asg_data['cluster_prefix']
    asg_name = f"{cluster_prefix}.{arcade_domain}"
    asg_lb_name = f"{cluster_prefix}-privatenlb-{arcade_safe_name}"

    failed = False
    if not asg.get_asg_info(asg_name):
        logging.info("Log relay ASG cluster does not exist.")
        failed = True

    if not alb.get_alb_status(asg_lb_name):
        logging.info("Log relay NLB does not exist.")
        failed = True

    if not dns.get_arcade_dns_record(arcade_name, asg_name):
        logging.info("Log relay DNS CNAME does not exist.")
        failed = True

    if failed:
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
