#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
log-relay -- Update the ARCADE scoped log relay.
'''

# @depends: python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Update the ARCADE scoped log relay."

import argparse
import logging
import os
from pprint import pprint
import sys

import boto3

from jinja2 import Template
from arclib import ami
from arclib import asg
from arclib import common
from arclib import log
from arclib import storage

#from log_relay import update_asg
#from log_relay import update_asg_template


def update_logrelay_asg(arcade_name: str,
                        gsd_data: dict) -> bool:
    """
    Update the ARCADE log relay.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """
    session = boto3.session.Session()
    bucket = storage.get_account_global_bucket(session)
    arcade_domain = arcade_name.replace('_', '-')
    asg_data = gsd_data['services']['asg']['service_options']
    cluster_prefix = asg_data['cluster_prefix']
    asg_name = f"{cluster_prefix}.{arcade_domain}"
    image_id = ami.get_ami_id(session, asg_data['node_ami_name'])
    user_data_file_expanded = f"userdata/{gsd_data['name']}/{asg_data['user_data_file']}"
    user_data_template = storage.s3_object_to_str(session, bucket, user_data_file_expanded)
    user_data = Template(user_data_template).render(asg_data)
    pprint(asg_data)
    print("------------")
    print(user_data_file_expanded)
    print("____________")
    print(user_data)

    delete_on_term = asg_data['vol_delete_on_termination']
    encrypted = asg_data['ebs_vol_encrypted']
    block_device_mappings = []
    if asg_data.get('ebs_root_vol_name'):
        block_device_mappings.append({
            'DeviceName': asg_data['ebs_root_vol_name'],
            'Ebs': {
                'VolumeSize': int(asg_data['ebs_root_vol_size']),
                'VolumeType': asg_data['ebs_root_vol_type'],
                'DeleteOnTermination': delete_on_term,
                'Encrypted': encrypted
            }
        })
    if asg_data.get('ebs_data_vol_name'):
        block_device_mappings.append({
            'DeviceName': asg_data['ebs_data_vol_name'],
            'Ebs': {
                'VolumeSize': int(asg_data['ebs_data_vol_size']),
                'VolumeType': asg_data['ebs_data_vol_type'],
                'DeleteOnTermination': delete_on_term,
                'Encrypted': encrypted
            }
        })

    if asg.asg_health(asg_name):
        status_config = update_asg_template(arcade_name,
                                                 cluster_prefix,
                                                 image_id,
                                                 user_data,
                                                 asg_data['instance_type'],
                                                 block_device_mappings)
        if status_config:
            status = update_asg(arcade_name,
                                cluster_prefix,
                                int(asg_data['asg_capacity']),
                                int(asg_data['asg_max_capacity'])
                               )
            if status != "HEALTHY":
                logging.error(status)
                return False
        else:
            logging.error(status_config)
            return False

    return True


def main():
    """
    %(prog)s - Create the ARCADE log relay ASG.
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path to filename in s3", required=True)

    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            parser.print_help()
            sys.exit(1)
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    session = boto3.session.Session()

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    if not gsd_data:
        sys.exit(1)
    pprint(gsd_data)

    # if not update_logrelay_asg(arcade_name, gsd_data):
    #     logging.info("Create log relay ASG cluster failed.")
    #     sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
