#!/usr/bin/env python3

import boto3
import sys
import argparse
import json
import hashlib
from datetime import datetime
from botocore.exceptions import ClientError
import tempfile
import logging


def validatejson(filehandle):
    try:
        json.load(filehandle)
    except ValueError as err:
        logging.error('JSON error: {}'.format(err))
        return False
    return True


def stdinFile(filehandle):
    lines = sys.stdin.readlines()
    for i in range(len(lines)):
        lines[i] = lines[i].replace('\n', '')
        filehandle.write(lines[i] + "\n")
    filehandle.seek(0)
    return lines


def hashfile(filehandle):
    hasher = hashlib.md5()
    buf = filehandle.read()
    hasher.update(buf.encode('utf-8'))
    return hasher.hexdigest()


def upload_file(file_name, bucket, object_name=None):
    if object_name is None:
        object_name = file_name

    s3_client = boto3.client('s3')
    try:
        response = s3_client.upload_file(file_name, bucket, object_name)
    except ClientError as e:
        logging.error('AWS error: {}'.format(e))
        return False
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file",
                        help="File to upload.  Use stdin if not given",
                        default="stdin")
    parser.add_argument("-b", "--bucket",
                        help="Bucket to upload to.  default is asd2021",
                        default="asd2021")
    parser.add_argument("-d", "--debug",
                        help="DEBUG information",
                        action="store_true")
    args = parser.parse_args()
    filename = args.file
    bucket = args.bucket
    if args.debug:
        logging.basicConfig(encoding='utf-8', level=logging.INFO)

    utcnow = datetime.utcnow()
    dateradix = utcnow.strftime("%y/%m/%d/%H/%M")

    if filename == "stdin":
        inputfile = tempfile.NamedTemporaryFile(mode='w+t')
        filename = inputfile.name
        stdinFile(inputfile)
        logging.info("upload stdin as {}".format(filename))
    else:
        inputfile = open(filename)
        logging.info("upload a file")

    if validatejson(inputfile):
        logging.info('Input file is {}'.format(filename))
        filehash = hashfile(inputfile)
        radixhash = '{}/{}.json'.format(dateradix, filehash)
        upload_file(filename, bucket, radixhash)
        print('{}/{}'.format(bucket, radixhash))
        inputfile.close()
    else:
        logging.error("bad json file")
        inputfile.close()
        sys.exit(2)


if __name__ == "__main__":
    main()
