#!/usr/bin/env python3

import logging
import os

from arclib import alb
from arclib.common import print_status


def main():
    """Use Environment variables to get actions done."""
    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    arcade_name = os.environ.get('GALAGA_ARCADE_NAME')

    logging.info(f'Updating Vault on {arcade_name}')


if __name__ == '__main__':
    main()
