#!/usr/bin/env python3
import boto3
import os
import sys
import logging
import json
import time
from python_terraform import *
from vault_import_vars import import_terraform_vars
from arclib.common import print_status
from arclib import grv


def dryrun_terraform_infra(terraform_dir: str, terraform_tfvars: dict, bucket: str):
    """Wrapper for deplyoing terraform

    Args:
        terraform_dir (str): [Directory path for terraform files]
        terraform_tfvars (dict): [TFVARS: Terraform variables]

    Returns: tuple of (return_code, stdout, stderr)
        [return_code]: [
            NOTE THIS IS ONLY FOR PLAN
            0 = means the plan worked. sys.exit(0) if no changes, otherwise sys.exit(1)
            1 = means there is a error in Terraform and nothing needs to be built due to errors. sys.exit(0) No action exit program.
        ]
    """
    vault_name = os.environ.get("GALAGA_CLUSTER_NAME")
    tf = Terraform(working_dir=terraform_dir)
    t_init = tf.init(lock_timeout="300s", backend_config={
        'bucket': bucket,
        'key': f'terraform/{vault_name}/{os.environ.get("ARCADE_NAME")}.tf',
        'region': os.environ.get("AWS_DEFAULT_REGION"),
    })
    return tf.plan(lock_timeout="900s", refresh=False, input=False, no_color=IsFlagged, var=terraform_tfvars, detailed_exitcode=IsNotFlagged)


def main():
    """
    Main Function to get a status of terraform using plan

    Error Codes:

    Terraform exit codes
    If dryrun_terraform_infra is executed then it has return codes: 0,1
    0 = means the plan worked. sys.exit(0) if no changes, otherwise sys.exit(1)
    1 = means there is a error in Terraform and nothing needs to be built due to errors. sys.exit(0) No action sys.exit program.

    GALAGA exit codes
    0 = means not to build
    1 = means to move on to the installer and build out the infrastructure.
    """

    logging.info('Starting execute of terraform')
    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    arcade_name = os.environ.get('ARCADE_NAME')
    if not arcade_name:
        print("Invalid arcade name")
        sys.exit(0)
    bucket = grv.get_infrastructure_bucket(arcade_name=arcade_name)
    vault_name = os.environ.get("GALAGA_CLUSTER_NAME")
    full_name = f"{arcade_name.replace('_', '-').replace('.', ' ').split()[0]}-{vault_name}"
    data = import_terraform_vars(grv_name=arcade_name)
    logging.info('Starting PLAN of terraform')
    return_code, stdout, stderr = dryrun_terraform_infra(terraform_dir=f"{os.environ.get('MYHIER')}/libexec/installer/vault/terraform_data", terraform_tfvars=data, bucket=bucket)

    status = {}
    status['keyfile'] = f"Shamir keys can be find in {bucket}/vaultauth/{full_name}-keys.json"
    status['stdout'] = stdout
    status['stderr'] = stderr
    logging.info(status)
    print_status(status)

    if return_code == 0 and 'No changes' in stdout:
        sys.exit(0)
    elif return_code == 1:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == '__main__':
    main()
