#!/usr/bin/env python3

import logging
import os
import sys
import json
import logging
from python_terraform import *
from arclib import storage, grv, common
from vault_import_vars import import_terraform_vars_del


def destroy_terraform_infra(terraform_dir: str, vars: dict, bucket: str):
    """Wrapper for deplyoing terraform

    Args:
        terraform_dir (str): [Directory path for terraform files]
        terraform_tfvars (dict): [TFVARS]

    Returns:
        [stdout]: [Terraform output]
    """
    vault_name = os.environ.get("GALAGA_CLUSTER_NAME")
    tf = Terraform(working_dir=terraform_dir)
    t_init = tf.init(backend_config={
        'bucket': bucket,
        'key': f'terraform/{vault_name}/{os.environ.get("ARCADE_NAME")}.tf',
        'region': os.environ.get("AWS_DEFAULT_REGION"),
    })
    return_code, stdout, stderr = tf.destroy(input=False, no_color=IsNotFlagged, force=IsNotFlagged, auto_approve=True, var=vars)
    if return_code == 0:
        return 0
    elif return_code == 1:
        return 1


def main():
    """Use Environment variables to get actions done."""
    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    if common.check_dryrun(os.path.basename(__file__)):
        sys.exit(0)

    arcade_name = os.getenv('ARCADE_NAME')

    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    bucket = grv.get_infrastructure_bucket(arcade_name=arcade_name)
    cluster_name = os.environ.get("GALAGA_CLUSTER_NAME")
    full_name = f"{arcade_name.replace('_', '-').replace('.', ' ').split()[0]}-{cluster_name}"
    vault_lock = storage.load_json(bucket, 'terraform/vault.json')
    logging.info(f'Removing Vault from Galaga on Arcade {arcade_name}')
    # the delete terraform_dir needs to be terraform_data and not full path from Galaga. Once Galaga uninstalls then this will need to be changed to full path.
    delete = destroy_terraform_infra(terraform_dir=f"{os.environ.get('MYHIER')}/libexec/installer/vault/terraform_data", vars=import_terraform_vars_del(grv_name=arcade_name), bucket=bucket)

    if delete == 0:
        if 'cluster_name' in vault_lock.keys():
            if vault_lock['cluster_name'] == full_name:
                storage.delete_s3_object(bucket, 'terraform/vault.json')
        storage.delete_s3_object(bucket, f'vaultauth/{full_name}-keys.json')
        storage.delete_s3_object(bucket, f'terraform/{cluster_name}/{arcade_name}.tf')
        logging.info(f"{arcade_name} vault has been deleted")
        sys.exit(0)
    elif delete == 1:
        sys.exit(1)


if __name__ == '__main__':
    main()
