#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
asteroids-create -- GALAGA create the asteroids components
'''

# @depends: python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Create the ASTEROIDS infrastructure."

import argparse
import logging
import os
from pprint import pprint
import sys

import boto3

from arclib import alb
from arclib import common
from arclib import log
from arclib import storage

from asteroids_eks import create_arcade_alb
from asteroids_eks import create_eks, create_eks_nodegroup
from asteroids_eks import apply_awsauth_configmap, connect_sg_to_alb
from asteroids_eks import apply_asteroids_fluentd_daemonset
from asteroids_eks import create_kubecost, create_namespace



def apply_kubecost(arcade_name: str, gsd_data: dict):
    create_kubecost_namespace = create_namespace(arcade_name=arcade_name, namespace='kubecost')
    if create_kubecost_namespace:
        # Create kubecost
        create = create_kubecost(arcade_name=arcade_name)
        if create:
            return True
        else:
            return False
    else:
        logging.info('Failed to create namespace')
        return False


def create_asteroids_albs(arcade_name: str, gsd_data: dict) -> bool:
    """
    Create the ASTEROIDS ALBs.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """

    for lb_type in [True, False]:
        alb_dict = alb.get_alb_dict(arcade_name, lb_type)
        if not alb.get_alb_status(alb_dict['name']):
            logging.info(f"Creating {alb_dict['name']} ALB on {arcade_name}")
            status = create_arcade_alb(arcade_name, lb_type)
            # pprint(status)
            if 'Error' in status:
                return False

    return True


def create_asteroids_eks(arcade_name: str,
                         gsd_data: dict) -> bool:
    """
    Create the ASTEROIDS EKS cluster.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """
    eks_data = gsd_data['services']['eks']['service_options']
    cluster_prefix = eks_data['cluster_prefix']
    eks_version = eks_data['eks_version']

    if not arcade_name or not cluster_prefix or not eks_version:
        print("Invalid arcade name or cluster prefix or eks version")
        return False

    logging.info(f"{cluster_prefix}-{arcade_name}")
    status = create_eks(arcade_name, cluster_prefix, eks_version)
    if 'Error' in status:
        return False

    return True


def create_asteroids_eks_nodegroup(arcade_name: str,
                                   gsd_data: dict) -> bool:
    """
    Create the ASTEROIDS EKS nodegroups.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """
    eks_data = gsd_data['services']['eks']['service_options']
    cluster_prefix = eks_data['cluster_prefix']
    cluster_name = f"{cluster_prefix}-{arcade_name.replace('.', '-')}"
    nodegroup_data = gsd_data['services']['nodegroup']['service_options']
    logging.info(cluster_name)

    for nodegroup_prefix in nodegroup_data.keys():
        nodegroup_options = nodegroup_data[nodegroup_prefix]
        nodegroup_options['nodegroup_prefix'] = nodegroup_prefix
        status = create_eks_nodegroup(arcade_name, cluster_prefix, nodegroup_options)
        if not status['status'] == "ACTIVE":
            logging.error(status)
            return False

    if not apply_awsauth_configmap(arcade_name, cluster_prefix):
        logging.error("awsauth configmap problem")
        return False

    if not connect_sg_to_alb(arcade_name, cluster_name, False):
        logging.error("Did not connect EKS to ALB Private")
        return False

    if not connect_sg_to_alb(arcade_name, cluster_name, True):
        logging.error("Did not connect EKS to ALB Public")
        return False

    return True


def create_asteroids_node_collector(arcade_name: str,
                                    gsd_data: dict) -> bool:
    """
    Create the Asteroid EKS node daemonset collector.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """
    cluster_prefix = 'log-relay'

    return apply_asteroids_fluentd_daemonset(arcade_name, cluster_prefix)


def main():
    """
    %(prog)s - Create the GALAGA asteroids
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path to filename in s3", required=True)

    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            parser.print_help()
            sys.exit(1)
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    tmp_dir = os.getenv("ATMP", '/tmp')

    session = boto3.session.Session()

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    
    if not gsd_data:
        sys.exit(1)
    
    pprint(gsd_data)

    if not create_asteroids_albs(arcade_name, gsd_data):
        logging.info("Create ASTEROIDS ALBs failed.")
        sys.exit(1)

    if not create_asteroids_eks(arcade_name, gsd_data):
        logging.info("Create ASTEROIDS EKS cluster failed.")
        sys.exit(1)

    if not create_asteroids_eks_nodegroup(arcade_name, gsd_data):
        logging.info("Create ASTEROIDS EKS nodegroups failed.")
        sys.exit(1)
    

    sys.exit(0)


if __name__ == '__main__':
    main()
