#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
eks-fluentd-create -- GALAGA create fluentd componet
'''

# @depends: python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Create the ASTEROIDS infrastructure."

import argparse
import logging
import os
from pprint import pprint
import sys
import yaml
import boto3

from arclib import common, log, storage, k8s, common, ecr
from kubernetes.client.rest import ApiException
from kubernetes import client
from botocore.exceptions import ClientError





def main():
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path with filename in s3", required=True)
    
    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            sys.exit(1)
    
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    tmp_dir = os.getenv("ATMP", '/tmp')

    session = boto3.session.Session()

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    
    if not gsd_data:
        sys.exit(1)
    
    pprint(gsd_data)

    service_options = gsd_data['services']['sumologic']['service_options']
    sumo_fluent_namespace = service_options['eks_namespace_name']
    
    try:
        k8s.load_arcade_k8s_config(arcade_name)
    except ClientError:
        return False

    k8s_client = client.CoreV1Api()

    lists = k8s_client.list_namespace(pretty=True)

    get_namespaces_list = [x.metadata.name for x in lists.items]
    

    if sumo_fluent_namespace not in get_namespaces_list:
      sys.exit(1)

    sys.exit(0)

if __name__ == '__main__':
    main()