#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
eks-fluentd-destroy -- GALAGA destroy fluentd componet
'''

# @depends: python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Create the ASTEROIDS infrastructure."

import argparse
import logging
import os
from pprint import pprint
import sys
import boto3
import yaml

from kubernetes.client.rest import ApiException
from kubernetes import client
from botocore.exceptions import ClientError

from arclib import k8s, common, ecr, log, storage

from eks_sumologic_fluentd import delete_sumologic, delete_namespace


def main():
    RS = common.ReturnStatus()
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path with filename in s3", required=True)
    
    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            sys.exit(1)
    
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    tmp_dir = os.getenv("ATMP", '/tmp')

    session = boto3.session.Session()

    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    
    if not gsd_data:
        sys.exit(1)
    
    pprint(gsd_data)

    service_options = gsd_data['services']['sumologic']['service_options']
    sumo_fluent_namespace = service_options['eks_namespace_name']
    
    
    # Start of delete

    list_of_kind = [
      'Job', 'Pod', 'PriorityClass', 'Prometheus', 'StatefulSet',
      'Deployment', 'DaemonSet', 'Service', 'ClusterRoleBinding',
      'ClusterRole', 'ConfigMap', 'Secret', 'ServiceAccount', 'PodDisruptionBudget',
      'PodSecurityPolicy', 'CRD'
    ]

    for kinds in list_of_kind:
      if not delete_sumologic(arcade_name=arcade_name, namespace=sumo_fluent_namespace, kind=kinds):
          pprint(f'ERROR: {kinds} failed to be deleted.')
          logging.info(f'ERROR: {kinds} failed to be deleted.')
          sys.exit(RS.NOT_OK)
    
    if not delete_namespace(arcade_name=arcade_name, namespace=sumo_fluent_namespace):
        pprint(f'ERROR: Namespace: {sumo_fluent_namespace} failed to be deleted.')
        logging.info(f'ERROR: Namespace: {sumo_fluent_namespace} failed to be deleted.')
        sys.exit(RS.NOT_OK)

      # End of delete
    
    sys.exit(0)

if __name__ == '__main__':
    main()