#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
prometheus-update -- GALAGA update of ARCADE/Account Infrastructure components.
'''

# @depends: boto3, python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Print status of ARCADE/Account components status."

import argparse 
import sys
import os
from pprint import pprint
import boto3
from arclib import log
from arclib import storage

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-A", "--arcade", help="Arcade Name")
    parser.add_argument("-p", "--path", help="Full path to filename in s3", required=True)
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    
    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)
    
    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            sys.exit(1)
    
    arcade_name = args.arcade
    
    session = boto3.session.Session()
    
    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']
        
    gsd_data = storage.load_arcade_json_to_dict(bucket, args.path)
    
    if not gsd_data:
        sys.exit(1)
    
    print('Placeholder for Prometheus Grafana Update')
    sys.exit(0)
    

if __name__ == '__main__':
    main()