#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

'''
secretsmanager-create -- GALAGA create the ARCADE secretsmanager
'''

# @depends: boto3, python (>=3.9)
__version__ = '0.1'
__author__ = 'Addepar Infrastructure Platform Tools Team <iptools@addepar.com>'
__description__ = "Create the ARCADE secretsmanager"


import argparse
import json
import logging
import os
from pprint import pprint
import secrets
import sys

import boto3
from botocore.exceptions import ClientError

from arclib import common
from arclib import grv
from arclib import log
from arclib import storage


# --------------------------------------------------------------------
#
# create_rds_default_creds
#
# --------------------------------------------------------------------
def create_rds_default_creds(arcade_name: str,
                             name='rds_default_credentials',
                             length=12):
    """
    Generates Default RDS creds for secrets manager per arcade

    Args:
        arcade_name (str): [arcade name]
        name (str, optional): [name of the secret]. Defaults to 'rds_default_credentials'.
        length (int, optional): [length of password]. Defaults to 12.

    Returns:
        [bool]: [True if Secret is created, False if the Secret failed to create]
    """
    arcade_trim = arcade_name.split('.')[0]
    create_p = secrets.token_urlsafe(length)
    s_value = {
        'username': f'{arcade_trim}_admin',
        'password': create_p
    }

    try:
        create_rds_cred = create_secret(
            arcade_name=arcade_name,
            name=name,
            secret_value=s_value
        )
    except ClientError as c_e:
        if c_e.response['Error']['Code'] == 'ResourceExistsException':
            logging.info("RDS Credentials already exist")
            return True
        print(c_e)
        logging.info(c_e)
        return False

    logging.info("Default RDS Credentials are set")
    return True


# --------------------------------------------------------------------
#
# create_secret
#
# --------------------------------------------------------------------
def create_secret(arcade_name: str,
                  name: str,
                  secret_value,
                  versions=None):
    """
    Creates a Secret In AWS Secrets Manager

    Args:
        arcade_name (str): [Name of the Arcade]
        name (str): [Name of the secret]
        secret_value : [The secret]
        versions ([type], optional): [description]. Defaults to None.

    Returns:
        [dict]: [Returns the ARN and Secret Name]
    """
    sm_client = boto3.client('secretsmanager')
    kwargs = {"Name": f"{arcade_name}/{name}",
              "Tags": [
                {
                    'Key': 'creator',
                    'Value': grv.aws_whoami(),
                },
                {
                    'Key': 'grv_name',
                    'Value': arcade_name,
                },
                {
                    'Key': 'grv_create_session_id',
                    'Value': grv.validate_create_id(arcade_name),
                },
                {
                    'Key': 'arcade_tool_provisioned',
                    'Value': common.get_account_id(),
                },
              ]
             }

    if isinstance(secret_value, dict):
        kwargs['SecretString'] = json.dumps(secret_value)

    elif isinstance(secret_value, str):
        kwargs['SecretString'] = secret_value

    elif isinstance(secret_value, bytes):
        kwargs['SecretBinary'] = secret_value

    if versions is None:
        response = sm_client.create_secret(**kwargs)
        logging.info(response)
    else:
        response = sm_client.create_secret(**kwargs)
        logging.info(response)
        response = update_secret_version(
            arcade_name=arcade_name,
            name=name,
            secret_value=secret_value,
            versions=[versions])

    return {'SecretName': response['Name'], 'SecretARN': response['ARN']}


# --------------------------------------------------------------------
#
# update_secret_version
#
# --------------------------------------------------------------------
def update_secret_version(arcade_name: str,
                          name: str,
                          secret_value: str,
                          versions=None):
    """
    Puts Value with Version in Secrets Manager

    Args:
        arcade_name (str): [Name of the Arcade]
        name (str): [Name of the secret]
        secret_value (str): [The secret]
        versions ([type], optional): [A version for the secret]. Defaults to None.
        ex: update_secret_version(arcade_name="my-test-arcade-str", name="my-test-secret-str", secret_value="test-secret-str-new-version", versions=["new-version"])

    Returns:
        [dict]: [aws api return]
    """
    sm_client = boto3.client("secretsmanager")
    kwargs = {"SecretId": f"{arcade_name}/{name}"}

    if isinstance(secret_value, dict):
        kwargs['SecretString'] = json.dumps(secret_value)

    elif isinstance(secret_value, str):
        kwargs['SecretString'] = secret_value

    elif isinstance(secret_value, bytes):
        kwargs['SecretBinary'] = secret_value

    if versions is not None:
        kwargs['VersionStages'] = versions

    response = sm_client.put_secret_value(**kwargs)

    return response


def create_arcade_secretsmanager(arcade_name:str,
                                 gsd_data: dict) -> bool:
    """
    Create the ARCADE SecretsManager.

    Args:
        arcade_name (str): The name of the ARCADE
        gsd_data (dict): The dict of GSD data

    Returns:
        bool: Success or failure
    """
    MANAGED_POLICY = {
        "Version": "2012-10-17",
        "Statement": {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:CreateSecret",
                "secretsmanager:DescribeSecret",
                "secretsmanager:DeleteSecret",
                "secretsmanager:GetRandomPassword",
                "secretsmanager:GetSecretValue",
                "secretsmanager:ListSecretVersionIds",
                "secretsmanager:ListSecrets",
                "secretsmanager:PutSecretValue",
                "secretsmanager:UpdateSecret",
                "sts:AssumeRoleWithWebIdentity"
            ],
            "Resource": "*"
        }
    }

    session = boto3.session.Session()
    iam_client = session.client('iam')
    arcade_trim = arcade_name.split('.')[0]

    if not grv.check_if_arcade_policy(arcade_name, 'SecretsManager'):
        logging.info("Creating parameterstore policy")
        try:
            # Create Policy
            response = iam_client.create_policy(
                PolicyName=f"{arcade_trim}-SecretsManager",
                PolicyDocument=json.dumps(MANAGED_POLICY))
            logging.info(response)
        except iam_client.exceptions.EntityAlreadyExistsException as c_e:
            logging.info(c_e)
            return False

    if not create_rds_default_creds(arcade_name):
        return False

    return True


def main():
    """
    %(prog)s - GALAGA create the ARCADE/Account infrastructure components.
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("-A", "--arcade", help='Arcade Name')
    parser.add_argument("--gsd", action="store_true", help="Use Account bucket not ARCADE bucket")
    parser.add_argument("-p", "--path", help="Full path to filename in s3")

    log.add_log_level_argument(parser)
    args = parser.parse_args()
    log.set_log_level(args.verbose)

    if not args.arcade:
        args.arcade = os.getenv('ARCADE_NAME')
        if not args.arcade:
            print("Arcade name missing, use -A/--arcade")
            parser.print_help()
            sys.exit(1)
    arcade_name = args.arcade
    os.environ["AWS_DEFAULT_REGION"] = common.get_arcade_region(arcade_name)

    session = boto3.session.Session()
    if args.gsd:
        bucket = storage.get_account_global_bucket(session)
    else:
        bucket = storage.get_arcade_buckets(session, arcade_name)['infrastructure']

    if args.path:
        gsd_data = storage.s3_json_to_dict(session, bucket, f"{args.path}")
        if not gsd_data:
            sys.exit(1)
    else:
        gsd_data = {
                    "name": "secretsmanager",
                    "component_type": "secretsmanager",
                    "version": 1,
                    "description": "Data for SecretsManager",
                    "services": {
                        "secretsmanager": {
                            "service_options": {}
                        }
                    }
                   }

    pprint(gsd_data)

    if not create_arcade_secretsmanager(arcade_name, gsd_data):
        logging.info("Create ARCADE SecretsManager failed.")
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
