# Source: sumologic/templates/setup/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: arcade-fluentd-sumologic-setup
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: arcade-fluentd-sumologic
    chart: "sumologic-2.18.1"
    release: "arcade-fluentd"
    heritage: "Helm"
spec:
  template:
    metadata:
      annotations:
      labels:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: arcade-fluentd-sumologic-setup
      volumes:
      - name: setup
        configMap:
          name: arcade-fluentd-sumologic-setup
          defaultMode: 0777
      - name: custom
        configMap:
          name: arcade-fluentd-sumologic-setup-custom
          defaultMode: 0777
      containers:
      - name: setup
        image: public.ecr.aws/sumologic/kubernetes-setup:3.4.0
        imagePullPolicy: IfNotPresent
        command: ["/etc/terraform/setup.sh"]
        resources:
          limits:
            cpu: 2000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 64Mi
        volumeMounts:
        - name: setup
          mountPath: /etc/terraform
        - name: custom
          mountPath: /customer-scripts
        envFrom:
        - secretRef:
            name: arcade-fluentd-sumologic-setup
        env:
        - name: SUMOLOGIC_BASE_URL
          value: 
        - name: HTTP_PROXY
          value: 
        - name: HTTPS_PROXY
          value: 
        - name: NO_PROXY
          value: kubernetes.default.svc
      securityContext:
        runAsUser: 999